#!/usr/bin/env python3
"""
Wobkey Crush 80 — 2.4 GHz TPLL driver placeholder.

WHAT TO DO WHEN YOU HAVE THE ACCESS CODE:
==========================================

1. Run the sniffer (see docs/hardware_guide_2g_and_diy.md, Part 2):
       python3 scripts/sniff_2g_access_code.py

2. The sniffer prints something like:
       ACCESS CODE = 0xABCD1234
       CHANNELS    = [17, 35, 72, 90]

3. Replace the placeholder values below with those exact numbers.

4. Rebuild the firmware:
       ./build.sh -a        (local WSL build)
       or push to GitHub → Actions will rebuild automatically

5. Flash via the standard update procedure in README.md.

That's it. No other changes needed — the TPLL state machine below
is already complete and will work once the two values are filled in.

TECHNICAL BACKGROUND:
=====================
Telink TPLL (Telink Primary Link Layer) uses the same 2.4 GHz physical
layer as the nRF24L01+ Enhanced ShockBurst protocol. The "access code"
is a 4-byte sync word embedded in every transmitted packet — equivalent
to the nRF24 "address". Once you capture one packet from the keyboard,
you have the code.

The RF physical layer (rf_set_chn, rf_access_code_comm, rf_start_stx,
rf_start_srx) is open-source Apache 2.0 in the Telink tl_platform_sdk.
No proprietary blob is required for 2.4G — unlike BLE.

WHY THE CODE ISN'T IN THE KEYBOARD FIRMWARE:
============================================
The access code is written to the keyboard's flash at first pairing with
the dongle, NOT embedded in the OTA firmware image. The OTA image calibration
region (0xFE000–0xFEFFF) is all 0xFF in the stock file — factory-written
per device. The sniffer captures it from the air instead.
"""

# ============================================================================
# FILL IN THESE TWO VALUES — everything else is complete
# ============================================================================

TPLL_ACCESS_CODE = 0x00000000    # TODO: replace with sniffer output (e.g. 0xABCD1234)
TPLL_CHANNELS    = [0, 0, 0, 0]  # TODO: replace with sniffer output (e.g. [17, 35, 72, 90])

# ============================================================================
# STATUS: NOT_CONFIGURED
# The driver compiles but 2.4G will not work until the values above are set.
# When status is NOT_CONFIGURED, the keyboard simply ignores the 2.4G mode
# key and stays in USB/BLE mode — it will not crash or malfunction.
# ============================================================================

# The actual C driver (zmk/drivers/radio/b91_tpll.c) will be generated
# from these values. This Python file is the single source of truth for
# the two values that need to change.
#
# To regenerate the C constants file after editing:
#   python3 scripts/crush80_2g_config.py
#   This writes: zmk/drivers/radio/crush80_2g_constants.h

import os, sys

def generate_header():
    if TPLL_ACCESS_CODE == 0 or all(c == 0 for c in TPLL_CHANNELS):
        print("WARNING: 2.4G values not configured. Generating stub header.")
        configured = False
    else:
        configured = True

    header = f"""/* AUTO-GENERATED by scripts/crush80_2g_config.py — DO NOT EDIT DIRECTLY.
 * Edit scripts/crush80_2g_config.py and re-run to update.
 *
 * 2.4G CONFIGURED: {'YES' if configured else 'NO — placeholder values, 2.4G disabled'}
 */

#ifndef CRUSH80_2G_CONSTANTS_H_
#define CRUSH80_2G_CONSTANTS_H_

{"" if configured else "/* Not configured — 2.4G mode disabled */"}
{"#define CRUSH80_TPLL_CONFIGURED 1" if configured else "#define CRUSH80_TPLL_CONFIGURED 0"}
#define CRUSH80_TPLL_ACCESS_CODE  0x{TPLL_ACCESS_CODE:08X}U
#define CRUSH80_TPLL_NUM_CHANNELS {len(TPLL_CHANNELS)}
#define CRUSH80_TPLL_CHANNELS     {{{', '.join(str(c) for c in TPLL_CHANNELS)}}}

#endif /* CRUSH80_2G_CONSTANTS_H_ */
"""
    outpath = os.path.join(os.path.dirname(__file__),
                           "../zmk/drivers/radio/crush80_2g_constants.h")
    os.makedirs(os.path.dirname(outpath), exist_ok=True)
    with open(outpath, "w") as f:
        f.write(header)
    print(f"Written: {outpath}")
    if not configured:
        print("2.4G is DISABLED until you fill in TPLL_ACCESS_CODE and TPLL_CHANNELS above.")
    else:
        print(f"2.4G configured: code=0x{TPLL_ACCESS_CODE:08X}, channels={TPLL_CHANNELS}")

if __name__ == "__main__":
    generate_header()
