/* AUTO-GENERATED by scripts/crush80_2g_config.py — DO NOT EDIT DIRECTLY.
 * Edit scripts/crush80_2g_config.py and re-run to update.
 *
 * 2.4G CONFIGURED: NO — placeholder values, 2.4G disabled
 */

#ifndef CRUSH80_2G_CONSTANTS_H_
#define CRUSH80_2G_CONSTANTS_H_

/* Not configured — 2.4G mode disabled */
#define CRUSH80_TPLL_CONFIGURED 0
#define CRUSH80_TPLL_ACCESS_CODE  0x00000000U
#define CRUSH80_TPLL_NUM_CHANNELS 4
#define CRUSH80_TPLL_CHANNELS     {0, 0, 0, 0}

#endif /* CRUSH80_2G_CONSTANTS_H_ */
